### ISSUE TITLE
Environmental Variables

### ISSUE THREAD

**Issue by onabee** [onabee/The-Little-Things#2]
So I've set an environment variable for an API key, I set it using the export command in my terminal. When I load the page, though, there's an error that says "process is not defined", referring to line 14 in my controller file that says process.env.user_key. I've been trying to solve this for like 2 hours. I tried using grunt to store my variable and do it that way but it fucked it up even more.

**Comment by phlco** [comment]
I don't see `process.env.user_key` anywhere in your code.

I do see an API key in your `main.js` Becareful because that key "787cbde1d6e95dbb894829b4668509a3" has numbers and letters in it, so your code will break unless you make it a string.

`process.env` is only in Node.  Do you have a server?

**Comment by phlco** [comment]
https://github.com/onabee/The-Little-Things/blob/ac2ec5ccded4dbb8152e8241f20b166ff288410f/public/js/charities_controller.js

This is client-side code, so it runs in the browser not node. There is no process.env.

If you want to have it in your client side code you'll need to first access it in `app.js` and then pass it down to the client.  Perhaps in an EJS file?

**Comment by onabee** [comment]
Ok. A lot of solutions are suggesting gulp so I suppose I'll try and use that.

**Comment by onabee** [comment]
Thank you for the help

**Comment by onabee** [comment]
I'm also a little confused though. Are Node, Express and Angular all separate types of apps then? Because I thought express and angular were node packages. Can you help me separate this in my head please?

**Comment by onabee** [comment]
Also, this is the link I saw that led me to have it in my controller: http://www.sitepoint.com/api-calls-angularjs-http-service/
